# Generated by Django 3.1.2 on 2020-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(db_column='cases', null=True)),
                ('county', models.CharField(db_column='county', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Covid-19-cases',
            },
        ),
    ]
